services:
  backend:
    build: .
    image: albaeud/futsal-backend
    container_name: futsal-backend
    restart: always
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    networks:
      - futsal-network

networks:
  futsal-network:
    external: true
