services:
  database:
    image: postgres:latest
    container_name: futsal-postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5433:${POSTGRES_PORT}"
    volumes:
      - futsal_pgdata:/var/lib/postgresql/data
    networks:
      - futsal-network

volumes:
  futsal_pgdata:

networks:
  futsal-network:
    external: true
